- name: update hosts file
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    regexp: '.*{{ item }}$'
  with_items: "{{ groups.all }}"

- name: update host name
  hostname:
    name: "{{ inventory_hostname }}"
